// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// // Firebase options import disabled
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASCLblwqz_6VhFUmrBzDPbnN6xeeI63eU',
    appId: '1:896977967332:web:bd7affaab9f3db25bf34f1',
    messagingSenderId: '896977967332',
    projectId: 'ekosatsss',
    authDomain: 'ekosatsss.firebaseapp.com',
    storageBucket: 'ekosatsss.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGTo05CLfG0oQKR4dbO3V7fwWwYR841Go',
    appId: '1:896977967332:android:3f7be56b2bb6afd6bf34f1',
    messagingSenderId: '896977967332',
    projectId: 'ekosatsss',
    storageBucket: 'ekosatsss.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBt_7iFv4F4ZYJ88k9dMa4SWYmA_JCFCds',
    appId: '1:896977967332:ios:e7202bb7adc979f6bf34f1',
    messagingSenderId: '896977967332',
    projectId: 'ekosatsss',
    storageBucket: 'ekosatsss.firebasestorage.app',
    iosBundleId: 'com.example.ekosatsss',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBt_7iFv4F4ZYJ88k9dMa4SWYmA_JCFCds',
    appId: '1:896977967332:ios:e7202bb7adc979f6bf34f1',
    messagingSenderId: '896977967332',
    projectId: 'ekosatsss',
    storageBucket: 'ekosatsss.firebasestorage.app',
    iosBundleId: 'com.example.ekosatsss',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyASCLblwqz_6VhFUmrBzDPbnN6xeeI63eU',
    appId: '1:896977967332:web:8cacbf245fb25f35bf34f1',
    messagingSenderId: '896977967332',
    projectId: 'ekosatsss',
    authDomain: 'ekosatsss.firebaseapp.com',
    storageBucket: 'ekosatsss.firebasestorage.app',
  );
}

